

// ------------------------------------------------------------------------------------------------
// This code was generated by EntityFramework Reverse POCO Generator (http://www.reversepoco.com/).
// Created by Simon Hughes (https://about.me/simon.hughes).
//
// Do not make changes directly to this file - edit the template instead.
//
// The following connection settings were used to generate this file:
//     Configuration file:     "FenixAvtoZapciasty.Data\Web.config"
//     Connection String Name: "AutoPartsEntities"
//     Connection String:      "metadata=res://*/DataContext.AutoPartsModel.csdl|res://*/DataContext.AutoPartsModel.ssdl|res://*/DataContext.AutoPartsModel.msl;provider=System.Data.SqlClient;provider connection string="data source=(LocalDB)\MSSQLLocalDB;attachdbfilename=C:\Users\Vasyl Laptop\Documents\FenixAvtoZapciasty\FenixAvtoZapciasty.Data\App_Data\\AutoParts.mdf;integrated security=True;MultipleActiveResultSets=True;App=EntityFramework""
// ------------------------------------------------------------------------------------------------

// ------------------------------------------------------------------------------------------------
// Failed to load provider "System.Data.EntityClient" - Unable to find the requested .Net Framework Data Provider.  It may not be installed.
// ------------------------------------------------------------------------------------------------

