//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FenixAvtoZapciasty.Data.DataContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class CarSubmodel
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public Nullable<int> ReleaseYear { get; set; }
        public int CarModelId { get; set; }
    
        public virtual CarModel CarModel { get; set; }
    }
}
